app:
  name: tanjl_im_receive_dev
  version: 1.0.0
  host: ""
  run_mode: info
  auth:
    secret: lalala
server:
  http:
    out_addr: 192.168.3.10:31002
    port: 31002
    read_timeout: 10
    write_timeout: 10
    ws:
      websocket_max_conn_num: 100
      websocket_time_out: 60
      websocket_max_msg_len: 10000
  grpc:
    port: 31003
    ip: 127.0.0.1
    register_name: "pool"
log:
  log_path:
  log_level: errors
  log_encode_mod: console
  is_console: true
data:
  mongo:
    url: mongodb://cny:123@127.0.0.1:27018/?authSource=admin
    database: im_srv
  redis:
    addr: 127.0.0.1:6378
    password: 123456
  kafka:
    addr: 127.0.0.1:9093
    topics: [im_msg]


third_party:
  email:
    sender:
    name:
    pass:
    host: smtp.163.com
    port: 465