// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: pb_msg.proto

package pb_msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendID           string `protobuf:"bytes,1,opt,name=sendID,proto3" json:"sendID,omitempty"` //发送者id
	RecvID           string `protobuf:"bytes,2,opt,name=recvID,proto3" json:"recvID,omitempty"`
	GroupID          string `protobuf:"bytes,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
	SenderPlatformID int32  `protobuf:"varint,4,opt,name=senderPlatformID,proto3" json:"senderPlatformID,omitempty"` //发送者平台ID，暂时无用
	SenderNickname   string `protobuf:"bytes,5,opt,name=senderNickname,proto3" json:"senderNickname,omitempty"`
	SenderFaceURL    string `protobuf:"bytes,6,opt,name=senderFaceURL,proto3" json:"senderFaceURL,omitempty"`
	SessionType      int32  `protobuf:"varint,7,opt,name=sessionType,proto3" json:"sessionType,omitempty"` //会话类型，0为单人，1为群组
	ContentType      int32  `protobuf:"varint,8,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Content          string `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	SendTime         int64  `protobuf:"varint,10,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	Status           int32  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	File             []byte `protobuf:"bytes,12,opt,name=file,proto3" json:"file,omitempty"`
	FileName         string `protobuf:"bytes,13,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize         int32  `protobuf:"varint,14,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	SelfID           string `protobuf:"bytes,15,opt,name=selfID,proto3" json:"selfID,omitempty"` //获取历史消息时的接收UID
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_pb_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *Msg) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *Msg) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *Msg) GetSenderPlatformID() int32 {
	if x != nil {
		return x.SenderPlatformID
	}
	return 0
}

func (x *Msg) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *Msg) GetSenderFaceURL() string {
	if x != nil {
		return x.SenderFaceURL
	}
	return ""
}

func (x *Msg) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *Msg) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *Msg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Msg) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Msg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Msg) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Msg) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Msg) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Msg) GetSelfID() string {
	if x != nil {
		return x.SelfID
	}
	return ""
}

type ErrRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *ErrRsp) Reset() {
	*x = ErrRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrRsp) ProtoMessage() {}

func (x *ErrRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrRsp.ProtoReflect.Descriptor instead.
func (*ErrRsp) Descriptor() ([]byte, []int) {
	return file_pb_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ErrRsp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *ErrRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_pb_msg_proto protoreflect.FileDescriptor

var file_pb_msg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0xbf, 0x03, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x76, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x76, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x46, 0x61, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x46, 0x61, 0x63, 0x65, 0x55,
	0x52, 0x4c, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x66, 0x49, 0x44, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6c, 0x66, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x52,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x4d, 0x73, 0x67, 0x32, 0x30, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x23, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x5f, 0x6d,
	0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e,
	0x45, 0x72, 0x72, 0x52, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x5f,
	0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_proto_rawDescOnce sync.Once
	file_pb_msg_proto_rawDescData = file_pb_msg_proto_rawDesc
)

func file_pb_msg_proto_rawDescGZIP() []byte {
	file_pb_msg_proto_rawDescOnce.Do(func() {
		file_pb_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_proto_rawDescData)
	})
	return file_pb_msg_proto_rawDescData
}

var file_pb_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_msg_proto_goTypes = []interface{}{
	(*Msg)(nil),    // 0: pb_msg.Msg
	(*ErrRsp)(nil), // 1: pb_msg.ErrRsp
}
var file_pb_msg_proto_depIdxs = []int32{
	0, // 0: pb_msg.MsgServer.Push:input_type -> pb_msg.Msg
	1, // 1: pb_msg.MsgServer.Push:output_type -> pb_msg.ErrRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_msg_proto_init() }
func file_pb_msg_proto_init() {
	if File_pb_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_msg_proto_goTypes,
		DependencyIndexes: file_pb_msg_proto_depIdxs,
		MessageInfos:      file_pb_msg_proto_msgTypes,
	}.Build()
	File_pb_msg_proto = out.File
	file_pb_msg_proto_rawDesc = nil
	file_pb_msg_proto_goTypes = nil
	file_pb_msg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MsgServerClient is the client API for MsgServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgServerClient interface {
	Push(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*ErrRsp, error)
}

type msgServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgServerClient(cc grpc.ClientConnInterface) MsgServerClient {
	return &msgServerClient{cc}
}

func (c *msgServerClient) Push(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*ErrRsp, error) {
	out := new(ErrRsp)
	err := c.cc.Invoke(ctx, "/pb_msg.MsgServer/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServerServer is the server API for MsgServer service.
type MsgServerServer interface {
	Push(context.Context, *Msg) (*ErrRsp, error)
}

// UnimplementedMsgServerServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServerServer struct {
}

func (*UnimplementedMsgServerServer) Push(context.Context, *Msg) (*ErrRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}

func RegisterMsgServerServer(s *grpc.Server, srv MsgServerServer) {
	s.RegisterService(&_MsgServer_serviceDesc, srv)
}

func _MsgServer_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServerServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_msg.MsgServer/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServerServer).Push(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_msg.MsgServer",
	HandlerType: (*MsgServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _MsgServer_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_msg.proto",
}
